
import { StudySection, AppTheme, THEMES } from "../types";

export const exportToPptx = async (sections: StudySection[], fileName: string) => {
  if (!window.PptxGenJS) {
    throw new Error("PPTX generator not loaded");
  }
  
  const pres = new window.PptxGenJS();
  pres.layout = "LAYOUT_16x9";
  
  // Clean filename for title
  const cleanName = fileName.replace(/\.[^/.]+$/, "");
  pres.title = cleanName;

  // 1. Title Slide
  let slide = pres.addSlide();
  slide.background = { color: "F0F9FF" }; // Brand-50
  
  slide.addText("Bilingual Study Guide", { 
    x: 0.5, y: 2, w: "90%", fontSize: 36, color: "0284C7", bold: true, align: "center", fontFace: "Arial" 
  });
  slide.addText(`Based on: ${cleanName}`, { 
    x: 0.5, y: 3, w: "90%", fontSize: 18, color: "64748B", align: "center", fontFace: "Arial" 
  });
  slide.addText("Generated by Bilingual Scholar", { 
    x: 0.5, y: 6.5, w: "90%", fontSize: 12, color: "94A3B8", align: "center", fontFace: "Arial" 
  });

  // 2. Section Slides
  sections.forEach((section) => {
    // A. Section Title Slide
    let sectionSlide = pres.addSlide();
    sectionSlide.background = { color: "0284C7" }; // Brand-600
    sectionSlide.addText(section.topic, { 
      x: 0.5, y: 3, w: "90%", fontSize: 32, color: "FFFFFF", bold: true, align: "center", fontFace: "Arial" 
    });

    // B. Content Slides (Split into chunks for readability)
    const chunkSize = 3;
    for (let i = 0; i < section.content.length; i += chunkSize) {
      const chunk = section.content.slice(i, i + chunkSize);
      let contentSlide = pres.addSlide();
      
      // Header
      contentSlide.addText(section.topic, { 
        x: 0.5, y: 0.3, w: "80%", fontSize: 14, color: "94A3B8", fontFace: "Arial" 
      });
      contentSlide.addShape(pres.ShapeType.line, { 
        x: 0.5, y: 0.7, w: "92%", h: 0, line: "E2E8F0" 
      });

      // Column Headers
      contentSlide.addText("English", { 
        x: 0.5, y: 1.0, w: 4.5, fontSize: 14, bold: true, color: "0284C7", fontFace: "Arial" 
      });
      contentSlide.addText("Chinese / 中文", { 
        x: 5.2, y: 1.0, w: 4.5, fontSize: 14, bold: true, color: "0284C7", fontFace: "Microsoft YaHei" 
      });

      // Content Rows
      let currentY = 1.6;
      chunk.forEach((point) => {
        const enText = point.keyTerm ? `[${point.keyTerm}] ${point.english}` : point.english;
        
        // English Column
        contentSlide.addText(enText, { 
          x: 0.5, y: currentY, w: 4.5, fontSize: 12, color: "334155", valign: "top", fontFace: "Arial", bullet: true
        });
        
        // Chinese Column
        contentSlide.addText(point.chinese, { 
          x: 5.2, y: currentY, w: 4.5, fontSize: 12, color: "334155", valign: "top", fontFace: "Microsoft YaHei" 
        });
        
        currentY += 1.8; // Approximate height per row
      });
      
      // Footer page number if needed
      contentSlide.addText("Bilingual Scholar", { x: 11.5, y: 7.0, fontSize: 10, color: "CBD5E1" });
    }
  });

  await pres.writeFile({ fileName: `${cleanName}_StudyGuide.pptx` });
};

// Helper to hex
const hexToRgb = (hex: string) => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : null;
};

export const exportToPdf = async (fileName: string, theme: AppTheme = THEMES[0]) => {
   if (!window.jspdf || !window.html2canvas) {
    throw new Error("PDF generator not loaded");
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF('p', 'mm', 'a4');
  const pdfWidth = doc.internal.pageSize.getWidth();
  const pdfHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  
  // Title Page
  const bgRgb = hexToRgb(theme.colors.bg);
  if(bgRgb) doc.setFillColor(bgRgb.r, bgRgb.g, bgRgb.b);
  else doc.setFillColor(240, 249, 255);
  
  doc.rect(0, 0, pdfWidth, pdfHeight, 'F');
  
  doc.setFontSize(28);
  
  const primRgb = hexToRgb(theme.colors.primary);
  if(primRgb) doc.setTextColor(primRgb.r, primRgb.g, primRgb.b);
  else doc.setTextColor(2, 132, 199);

  doc.text("Bilingual Study Guide", pdfWidth / 2, 80, { align: 'center' });
  
  doc.setFontSize(14);
  const textRgb = hexToRgb(theme.colors.subtext);
  if(textRgb) doc.setTextColor(textRgb.r, textRgb.g, textRgb.b);
  else doc.setTextColor(100, 116, 139);

  doc.text(`Source: ${fileName}`, pdfWidth / 2, 95, { align: 'center' });

  doc.setFontSize(10);
  doc.text("Generated by Bilingual Scholar", pdfWidth / 2, 280, { align: 'center' });

  let currentY = 15;
  doc.addPage();
  
  // Page Background for content pages
  if(bgRgb) doc.setFillColor(bgRgb.r, bgRgb.g, bgRgb.b);
  doc.rect(0,0, pdfWidth, pdfHeight, 'F');

  // Capture Sections
  const elements = document.getElementsByClassName('study-section-export');
  
  for (let i = 0; i < elements.length; i++) {
    const element = elements[i] as HTMLElement;
    
    // High quality capture
    const canvas = await window.html2canvas(element, { 
        scale: 2, 
        useCORS: true,
        backgroundColor: theme.colors.card // Use theme card color
    });
    
    const imgData = canvas.toDataURL('image/png');
    const imgProps = doc.getImageProperties(imgData);
    
    // Calculate aspect ratio to fit width
    const imgWidth = pdfWidth - (margin * 2);
    const imgHeight = (imgProps.height * imgWidth) / imgProps.width;

    // Logic to handle page breaks
    if (currentY + imgHeight > pdfHeight - margin) {
      doc.addPage();
      if(bgRgb) doc.setFillColor(bgRgb.r, bgRgb.g, bgRgb.b);
      doc.rect(0,0, pdfWidth, pdfHeight, 'F');
      currentY = margin;
    }

    doc.addImage(imgData, 'PNG', margin, currentY, imgWidth, imgHeight);
    
    // Add padding after image
    currentY += imgHeight + 10;
  }

  doc.save(`${fileName.replace(/\.[^/.]+$/, "")}_StudyGuide.pdf`);
};
